# Generated by Django 5.2.15 on 2026-06-16 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название отчёта')),
                ('file', models.FileField(upload_to='reports/', verbose_name='Файл Excel')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('period', models.CharField(blank=True, max_length=300, verbose_name='Период')),
                ('vehicles_list', models.TextField(blank=True, verbose_name='Список ТС')),
                ('daily_norm_hours', models.FloatField(default=8.0, verbose_name='Норма работы в сутки (час)')),
                ('bulldozer_idle_norm_pct', models.FloatField(default=30.0, verbose_name='Норма холостого хода бульдозеров/погрузчиков (% от времени работы)')),
                ('excavator_downtime_norm_pct', models.FloatField(default=30.0, verbose_name='Норма времени простоя стрелы экскаваторов (% от времени работы)')),
                ('dumptruck_nomove_norm_pct', models.FloatField(default=40.0, verbose_name='Норма времени без движения самосвалов (% от времени работы)')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(default=0, verbose_name='№')),
                ('name', models.CharField(max_length=200, verbose_name='Название ТС')),
                ('group', models.CharField(max_length=100, verbose_name='Группа ТС')),
                ('date', models.CharField(max_length=50, verbose_name='Дата')),
                ('engine_time_sec', models.FloatField(verbose_name='Время работы двигателя (сек)')),
                ('engine_no_move_sec', models.FloatField(verbose_name='Время работы без движения (сек)')),
                ('engine_idle_sec', models.FloatField(verbose_name='Время холостого хода (сек)')),
                ('fuel_norm', models.FloatField(verbose_name='Норма расхода (л/ч)')),
                ('fuel_actual', models.FloatField(blank=True, null=True, verbose_name='Фактический расход (л)')),
                ('downtime_sec', models.FloatField(blank=True, null=True, verbose_name='Время простоя (сек)')),
                ('has_anomaly', models.BooleanField(default=False, verbose_name='Есть аномалия')),
                ('anomaly_details', models.JSONField(default=list, verbose_name='Описание аномалий')),
                ('fuel_efficiency', models.FloatField(blank=True, null=True, verbose_name='Расход к норме')),
                ('equipment_output', models.FloatField(blank=True, null=True, verbose_name='Выход техники')),
                ('type_efficiency', models.FloatField(blank=True, null=True, verbose_name='Эффективность (тип)')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.report', verbose_name='Отчёт')),
            ],
            options={
                'verbose_name': 'Запись по ТС',
                'verbose_name_plural': 'Записи по ТС',
                'ordering': ['row_number'],
            },
        ),
    ]
