# Generated by Django 5.2.15 on 2026-06-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='bulldozer_idle_norm_pct',
        ),
        migrations.RemoveField(
            model_name='report',
            name='daily_norm_hours',
        ),
        migrations.RemoveField(
            model_name='report',
            name='dumptruck_nomove_norm_pct',
        ),
        migrations.RemoveField(
            model_name='report',
            name='excavator_downtime_norm_pct',
        ),
        migrations.AddField(
            model_name='report',
            name='bulldozer_norm_sec',
            field=models.IntegerField(default=7200, verbose_name='Норма холостого хода бульдозеров/погрузчиков (сек)'),
        ),
        migrations.AddField(
            model_name='report',
            name='daily_norm_sec',
            field=models.IntegerField(default=28800, verbose_name='Норма работы в сутки (сек)'),
        ),
        migrations.AddField(
            model_name='report',
            name='dumptruck_norm_sec',
            field=models.IntegerField(default=10800, verbose_name='Норма времени без движения самосвалов (сек)'),
        ),
        migrations.AddField(
            model_name='report',
            name='excavator_norm_sec',
            field=models.IntegerField(default=7200, verbose_name='Норма времени простоя стрелы экскаваторов (сек)'),
        ),
        migrations.AlterField(
            model_name='vehiclerecord',
            name='downtime_sec',
            field=models.FloatField(blank=True, null=True, verbose_name='Время простоя стрелы (сек)'),
        ),
    ]
