# Generated by Django 4.2.30 on 2026-06-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_vehiclerecord_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerecord',
            name='date',
            field=models.CharField(max_length=50, verbose_name='Дата (день.месяц)'),
        ),
    ]
