# Generated by Django 5.2.15 on 2026-06-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_vehiclenorm_shift'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiclenorm',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vehiclenorm',
            name='date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Дата (день.месяц)'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclenorm',
            unique_together={('report', 'vehicle_name', 'shift', 'date')},
        ),
    ]
