# Generated by Django 5.2.15 on 2026-06-29 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_add_date_to_vehiclenorm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Вид поломки')),
            ],
            options={
                'verbose_name': 'Вид поломки',
                'verbose_name_plural': 'Виды поломок',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FailureCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Причина неисправности')),
            ],
            options={
                'verbose_name': 'Причина неисправности',
                'verbose_name_plural': 'Причины неисправности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название техники')),
                ('group', models.CharField(choices=[('Самосвалы', 'Самосвалы'), ('Экскаваторы', 'Экскаваторы'), ('Бульдозеры', 'Бульдозеры'), ('Погрузчики', 'Погрузчики'), ('АТЗ', 'АТЗ'), ('Вспомогательная техника', 'Вспомогательная техника')], max_length=100, verbose_name='Группа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.section', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Единица техники (мониторинг)',
                'verbose_name_plural': 'Техника (мониторинг)',
                'ordering': ['group', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор')),
                ('sensor_rpm', models.BooleanField(default=True, verbose_name='Обороты двигателя')),
                ('sensor_dut', models.BooleanField(default=True, verbose_name='ДУТ')),
                ('sensor_gps', models.BooleanField(default=True, verbose_name='GPS')),
                ('sensor_gsm', models.BooleanField(default=True, verbose_name='Связь')),
                ('sensor_arrow', models.BooleanField(blank=True, null=True, verbose_name='Стрела')),
                ('sensor_cube_port', models.BooleanField(blank=True, null=True, verbose_name='Cube/port')),
                ('sensor_uss', models.BooleanField(blank=True, null=True, verbose_name='УСС')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breakdown_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.breakdowntype', verbose_name='Вид поломки')),
                ('failure_cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.failurecause', verbose_name='Причина неисправности')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='analysis.monitoringvehicle', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'Запись мониторинга',
                'verbose_name_plural': 'Записи мониторинга',
                'ordering': ['-date', 'vehicle__order', 'vehicle__name'],
                'unique_together': {('vehicle', 'date')},
            },
        ),
    ]
