# Generated by Django 5.2.16 on 2026-07-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_smtpsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bulldozer_norm_sec',
            field=models.IntegerField(default=10800, verbose_name='Норма холостого хода бульдозеров/погрузчиков (сек)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='excavator_norm_sec',
            field=models.IntegerField(default=13200, verbose_name='Норма времени простоя стрелы экскаваторов (сек)'),
        ),
    ]
